// <auto-generated />
using Financify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financify.Migrations.TransactionDb
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20230427070445_TransactionMigration")]
    partial class TransactionMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Financify.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = "71d863b5-571f-499d-ae87-e0578a3fafae",
                            Amount = 10.99m,
                            Category = "Food",
                            UserId = "Pratik"
                        },
                        new
                        {
                            TransactionId = "993e3163-acdf-4825-818f-2ef703934883",
                            Amount = 50.00m,
                            Category = "Entertainment",
                            UserId = "Pratik"
                        },
                        new
                        {
                            TransactionId = "8869b9c7-60ce-4bda-9c45-50e57a424639",
                            Amount = 39.00m,
                            Category = "Food",
                            UserId = "Pratik"
                        },
                        new
                        {
                            TransactionId = "262235be-8fde-4c95-a74e-e236374647ce",
                            Amount = 26.00m,
                            Category = "Entertainment",
                            UserId = "Pratik"
                        },
                        new
                        {
                            TransactionId = "66e1f61e-66ce-4d5f-be03-e759eee7a244",
                            Amount = 10.99m,
                            Category = "Housing",
                            UserId = "Tyson"
                        },
                        new
                        {
                            TransactionId = "87d3ca8d-689a-43b5-ad5a-2f608058dd74",
                            Amount = 50.00m,
                            Category = "Food",
                            UserId = "Tyson"
                        },
                        new
                        {
                            TransactionId = "74362cbb-476d-40ea-9146-364f2be3f2fa",
                            Amount = 39.00m,
                            Category = "Other",
                            UserId = "Tyson"
                        },
                        new
                        {
                            TransactionId = "d5ff04a7-b217-4eb2-b349-495ae7c1b343",
                            Amount = 26.00m,
                            Category = "Entertainment",
                            UserId = "Tyson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
